INSERT INTO `catalogo` (`codigo`, `nombre`, `precio`, `descripcion`, `imagen`) VALUES 
(100305001, 'Camiseta Ellesse azul', 20, 'Clásica camiseta Prado de Ellesse. La camiseta presenta un diseño de cuello redondo y está fabricada en algodón 100%. Está rematada con el logo de Ellesse estampada mediante un molde sublimado. ', 'images/ellesse_t-shirt_blue.jpg'),
(100306001, 'Camiseta Fred Perry caoba', 25, 'Camiseta clásica de cuello redondo de Fred Perry. Presenta un cuello redondo ligeramente acanalado y con la corona de laurel bordada en el pecho. Fabricado a partir de algodón fino 100%.', 'images/fredperry_t-shirt_maghogany.jpg'),
(100306002, 'Camiseta Fred Perry rayas',  23, 'La camiseta "Breton striped" de Fred Perry. Rayas horizontales a lo largo de toda la camiseta con la corona de laurel marcada en el pecho. Fabricada a partir de algodón 100%.', 'images/fredperry_t-shirt_stripesbw.jpg'),
(100307001, 'Camiseta Henri Lloyd radar', 27, 'Camiseta Henri Lloyd Radar Tee. Diseño de manga corta y cuello redondo. Lleva bordado el logo en el pecho y nervaduras en el cuello. Fabricada en algodón 100%.', 'images/henrilloyd_t-shirt_radar.jpg');

INSERT INTO `catalogo` (`codigo`, `nombre`, `precio`, `descripcion`, `imagen`) VALUES 
(100305002, 'Camiseta Ellesse Bergamo', 25, 'Camiseta Bergamo de la temporada 2015 Ellesse. Impresión sublimada a gran escala en la parte frontal. Diseño de cuello redondo, fabricada 100% en algodón', 'images/ellesse_t-shirt_dante.jpg'),
(100305003, 'Camiseta Ellesse Dante', 22, 'Camiseta Dante de Ellesse de manga corta y un cuello acanalado. Impresiones de gran tamaño en el frontal. Logotipo de la marca del cosido en el brazo y detalle del logo en el costado finalizan esta elegante camiseta. Fabricada 100% en algodón', 'images/ellesse_t-shirt_dante.jpg');
